### ISSUE TITLE
Possibly provide a signed Nuget package

### ISSUE THREAD

**Issue by forgetaboutit** [sprache/Sprache#108]
It would be great if you could sign future releases, if it's not too much of a hassle.

Unfortunately, we have a lot of signed projects in our solutions which prevents referencing Sprache.

**Comment by nkreipke** [comment]
I have forked Sprache to provide a strong-named version: https://github.com/nkreipke/Sprache/tree/sign/2.2.0 (https://www.nuget.org/packages/Sprache.Signed)

I figured you weren't interested in merging it due to the discussion in issue #87. It's really a simple change, I can provide the PR however you'd need to generate your own SNK.

**Comment by forgetaboutit** [comment]
@nkreipke : Thank you for your efforts!
@nblumhardt : I believe it's fine to close this issue then. Anyone else interested in a signed assembly can use @nkreipke's version.

As far as we are concerned, we have abandoned signed assemblies for the most part. Some of the reasons for this have been outlined by [other people](https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/) far more eloquently than I could ever have.

**Comment by nblumhardt** [comment]
Ah yes, forgot about the earlier discussion :-) ... happy to close! :-)

**Comment by shenglol** [comment]
Hi @nkreipke, do you mind syncing the main repo and creating a new release for the signed package? The current version (2.2.0) has a dependency on `System.Private.Uri (4.3.0)` which is known to have some vulnerability issue.

**Comment by nkreipke** [comment]
@shenglol Done!
