### ISSUE TITLE
.NET Core 3.1

### ISSUE THREAD

**Issue by faso** [sprache/Sprache#152]
May I retarget the samples and whatever else is necessary to .NET Core 3.1?

**Comment by nblumhardt** [comment]
Sounds great; as long as it's possible to preserve the existing targets of the Sprache package itself 👍

**Comment by jzabroski** [comment]
@faso Technically, it should target netstandard2.1 not netcoreapp3.1.

**Comment by nblumhardt** [comment]
The samples are EXEs, IIRC, so netcoreapp3.1 would be the norm, there.

**Comment by jzabroski** [comment]
@nblumhardt Yes, the lib should add netstandard2.1 and the sample should use netcoreapp3.1

The reason why its good to target netstandard2.1 is due to the craziness that is ASP.NET and the diamond dependencies that form when you try to load a project with Sprache and ASP.NET dependencies into the same context.  By targeting netstandard2.1, you can avoid weird PackageReference resolution behavior.  <-- THIS TOOK ME THREE YEARS TO UNDERSTAND...

**Comment by nblumhardt** [comment]
@jzabroski 😆  ... I know the feeling!

There are still a couple of package dependencies in `netstandard2.1` which are part of the framework reference in `netcoreapp3.1`, so I've thrown up my hands and used it as a library target in a few places.

I can't help but feel we're heading for a new norm of including `netstandard2.0` for platform reach, and `net5` (or whatever its TFM is) for full features. The unification of .NET Fx, Core, and Mono makes high-version .NET Standard TFMs a bit redundant IMO.

Agreed `netstandard2.1` is a fine choice for the library portion of Sprache, though 👍

**Comment by MagicAndre1981** [comment]
The change from #153 included not needed dependencies for .net Standard 2.x, those are only required for ns1.x.

![image](https://user-images.githubusercontent.com/8274816/94520655-ee042e00-022c-11eb-818d-f5e5fcb69e47.png)

Can this be fixed?
