### ISSUE TITLE
Help getting started?

### ISSUE THREAD

**Issue by TheColonel2688** [sprache/Sprache#169]
So I have the following. These are the first 2 records of a text file that has a custom format. It is basically a list. Each record has 5 Items, They start with a `#` and end when they encounter the next #. Each item is an array of strings, delimited with the `|` pipe symbol.

The first line we can ignore for now.

So for each record, I need something like this

```
    class Record
    {
        public int Id {get;set;} //** first element of First line
        public List<string> Properties { get; set; }
        public List<List<string>> Parameters { get; set; }
        public List<List<string>> Alarm { get; set; }
        public List<List<string>> History { get; set; }
        public List<List<string>> ItemParameters { get; set; }
    }
```

So I would like to end up with a List<Record>

```
// 20.00 - Version
#1|SomeText and stuff|0|1| | |1|0| |
#Parameters
<[0]>|1|0|0|0|0|0.000000|0.000000|0.000000| | | |
#Alarm
#History
#ItemParameters
<[0]>|1|1|
#2|SomeMoreText|0|3| | |1|0| |
#Parameters
<[0]>|1|0|0|0|0|0.000000|0.000000|0.000000| | | |
<[1]>|1|0|0|0|0|0.000000|0.000000|0.000000| | | |
#Alarm
#History
#ItemParameters
<[0]>|1|1|
```

P.S. What is the difference between https://github.com/datalust/superpower and Sprache?

**Comment by nblumhardt** [comment]
Hi! Thanks for getting in touch.

RE getting started, the best way to do it is to pick out the smallest units of the grammar - say, a `Heading` rule representing `#Name`, and model those:

```csharp
class Heading
{
    public Heading(string name) { ...  }
}
```

It's not strictly necessary to create fine-grained types for everything, but it'll make everything easier to follow in the end (and you can map back to whatever data structure you need after parsing is done).

```csharp
static Parser<Heading> Heading =
    from _ in Parse.Char('#')
    from name in Parse.LetterOrDigit.Many().Text()
    select new Heading(name);
```

Then, once you've got `Heading` sorted out, you might create a `ValueList` (maybe it's type is `List<string>`), and then a `Section` parser that uses `Heading` and `ValueList` to parse a single `#Name` heading and the trailing lists of values.

Working from the small to the large is almost always easier, not least because you can test the tiny parsers as you go.

I wrote Superpower mainly to produce better error messages than Sprache can, in [Seq](https://datalust.co/seq)'s query parser, but it has a few other advantages (especially if you have to deal with comments).

Original reasoning for building it: https://nblumhardt.com/2016/09/superpower/

But the README is more up-to-date, and there are sample projects in its repository if you are keen to get a feel for the differences between the two.

Good luck and have fun! :)

**Comment by nblumhardt** [comment]
Ah also, sorry - there are quite a few people following the `sprache` and `superpower` tags on Stack Overflow, it's usually the quickest and most efficient way to get help if you're stuck at any point.

**Comment by TheColonel2688** [comment]
I am moving to use superpower. I posted a question on SO last but so far I haven't gotten a response.

Closing this and going a new issue on the superpower Repo
