### ISSUE TITLE
React on MS Sec Advisory CVE-2019-0820

### ISSUE THREAD

**Issue by mleutner** [sprache/Sprache#175]
Dear Maintainers,
please update package reference as advised by MS, see https://github.com/dotnet/announcements/issues/111

<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />

Best Regards

**Comment by nblumhardt** [comment]
Thanks for the note, Markus. From the link, it appears that (at least for supported platforms?) _System.Text.RegularExpressions_ is a facade over _System_, so the fix is to update your .NET install:

> How do I fix the issue?
>
> To fix the issue please install the latest version of .NET Core. If you have multiple versions of .NET Core installed you will need to install multiple runtimes, or SDKs depending on what you have installed.

However, we're also in the process of assembling a new release that drops support for obsolete/unsupported frameworks - just started with #173 - that also removes the explicit reference to _s.t.RegularExpressions_.
