### ISSUE TITLE
Question: why does IPositionAware.SetPos return new instance?

### ISSUE THREAD

**Issue by Thecentury** [sprache/Sprache#31]
Hi!

Why does IPositionAware<T>.SetPos return new instance of T?
What should I return in this method except the simplest option — just self?

Why this method does not return just void?

**Comment by nblumhardt** [comment]
I think the reason here is that other tokens might still refer to the input, and so would be made invalid by mutating the value (IIRC). As @rossipedia suggests, a lot of Sprache is very "functional", where this design approach works well.

If you still need a hand figuring out a solution here feel free to reopen, we may need some more examples of your scenario though. Cheers!
