### ISSUE TITLE
Sprache only works with strings!

### ISSUE THREAD

**Issue by SuperJMN** [sprache/Sprache#68]
Why not trying to generalize it to handle streams of T? In my case, I have language that is a stream of tokens (XamlInstruction). I cannot create a parser with Sprache because it only allows me to create parsers whose base input is a string. 

What about turning string inputs into IEnumerable<char>. I've tried to do it myself, but it seems you're working with the concept of "lines" that is to coupled with other concepts like carriage returns, that aren't applicable in the generalization I'm proposing.

**Comment by mpartipilo** [comment]
If I recall correctly, you can create a parser from anything. You just can't use most of the predefined methods that are available, and must recreate most of them yourself.

If you'd like to try another similar parser builder there's one available in the repo louthy/language-ext. When I checked it it was more generic, but had less features than Sprache.

Michelangelo P.

**Comment by nblumhardt** [comment]
There are a few limitations pretty much baked into Sprache - string-only input is one, and character-by-character parsing (no tokenization) is the other. Eventually after coming to grips with how the library works, both limitations become apparent, but imposing them makes it much easier to go from zero-to-parser without a lot of background knowledge.

I'd love to have a fully token-based/generic implementation otherwise similar to Sprache, but I think it's a separate project. Sprache is great for quick and easy text processing and should probably stay that way, but having a companion project that is token-based and generic would be a natural step forwards and let people (like we!) who've built large parsers on Sprache to migrate without too much pain... Thoughts?

**Comment by SuperJMN** [comment]
I agree! @nblumhardt. A new Project would be the way to go. Unfortunately, I don't feel like I'm the one to start it from scratch :(

**Comment by nblumhardt** [comment]
:-) Neither am I, to be honest .. I did create an early, very simple version of this, I will see if I can dig it out...

**Comment by nblumhardt** [comment]
Closing this one as it's not able to be actioned right now, but I'd love to hear from anyone who gives this a shot :-)

**Comment by nblumhardt** [comment]
@SuperJMN started: https://github.com/datalust/superpower

I'm realizing in the process what a nice sweet spot Sprache occupies. I'm getting better error messages (and handling some corner cases more elegantly) in my large test parser, but for quite a lot more effort. Worth it when the messages need to be displayed to end-users, but definitely more of a companion to Sprache parser than a "vnext" of it.

Having fun with it, but it's early days and not everything works particularly well just yet.... :-)
